# Generated by Django 5.1.1 on 2025-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_numer',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
    ]
