# Generated by Django 5.1.1 on 2025-01-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeeper', '0002_player_skill_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='skill_numer',
            new_name='power_index',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='skill_rank',
            new_name='skill_class',
        ),
    ]
