# Generated by Django 5.1.1 on 2025-01-22 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeeper', '0003_rename_skill_numer_player_power_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematchup',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamematchup',
            name='matchup_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamematchup',
            name='scores',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gamematchup',
            name='game_type',
            field=models.CharField(choices=[('8-Ball', '8-Ball'), ('9-Ball', '9-Ball'), ('10-Ball', '10-Ball')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamematchup',
            name='lag_loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lag_loser_games', to='scorekeeper.player'),
        ),
        migrations.AlterField(
            model_name='gamematchup',
            name='lag_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lag_winner_games', to='scorekeeper.player'),
        ),
        migrations.AlterField(
            model_name='gamematchup',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorekeeper.match'),
        ),
    ]
